/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package br.com.estudos.produtos.view;

import br.com.estudos.produtos.model.Usuario;
import br.com.estudos.produtos.view.contrato.IPrincipalView;

public class PrincipalFrame extends javax.swing.JFrame implements IPrincipalView {

    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
    }

    @Override
    public void exibir() {
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setVisible(true);
    }

    @Override
    public void fechar() {
        dispose();
    }

    @Override
    public void exibirMensagem(String texto) {
        javax.swing.JOptionPane.showMessageDialog(this, texto, "Atenção", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public boolean exibirConfirmacao(String texto) {
        return javax.swing.JOptionPane.showConfirmDialog(this, texto, "Confirmação",
                javax.swing.JOptionPane.YES_NO_OPTION) == javax.swing.JOptionPane.YES_OPTION;
    }

    @Override
    public void exibirUsuario(String nome, String perfil) {
        labelUsuario.setText("Usuário: " + nome + " (" + perfil + ")");
    }

    @Override
    public void configurarPerfil(String perfil) {
        boolean administrador = Usuario.ADMINISTRADOR.equals(perfil);
        boolean podeAcessarClientes = administrador
                || Usuario.ATENDENTE.equals(perfil);

        menuUsuarios.setVisible(administrador);
        menuClientes.setVisible(podeAcessarClientes);
    }

    @Override
    public void aoIncluir(Runnable acao) {
        Eventos.adicionarAcao(menuIncluir, acao);
    }

    @Override
    public void aoBuscar(Runnable acao) {
        Eventos.adicionarAcao(menuBuscar, acao);
    }

    @Override
    public void aoCategorias(Runnable acao) {
        Eventos.adicionarAcao(menuCategorias, acao);
    }

    @Override
    public void aoClientes(Runnable acao) {
        Eventos.adicionarAcao(menuClientes, acao);
    }

    @Override
    public void aoUsuarios(Runnable acao) {
        Eventos.adicionarAcao(menuUsuariosCadastro, acao);
    }

    @Override
    public void aoCalcular(Runnable acao) {
        Eventos.adicionarAcao(menuCalcular, acao);
    }

    @Override
    public void aoSair(Runnable acao) {
        Eventos.adicionarAcao(menuSair, acao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaCentral = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOperacao = new javax.swing.JMenu();
        menuCalcular = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        menuDados = new javax.swing.JMenu();
        menuProdutos = new javax.swing.JMenu();
        menuIncluir = new javax.swing.JMenuItem();
        menuBuscar = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuEntregadores = new javax.swing.JMenuItem();
        menuTaxasEntrega = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuUsuariosCadastro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POC Delivery");
        setPreferredSize(new java.awt.Dimension(860, 580));

        labelUsuario.setFont(new java.awt.Font("Dialog", 0, 16));
        labelUsuario.setText("Usuário:");

        menuOperacao.setText("Operação");

        menuCalcular.setText("Calcular preço de venda");
        menuOperacao.add(menuCalcular);

        menuSair.setText("Sair");
        menuOperacao.add(menuSair);

        jMenuBar1.add(menuOperacao);

        menuDados.setText("Dados");

        menuProdutos.setText("Produtos");

        menuIncluir.setText("Incluir produto");
        menuProdutos.add(menuIncluir);

        menuBuscar.setText("Buscar produtos");
        menuProdutos.add(menuBuscar);

        menuDados.add(menuProdutos);

        menuCategorias.setText("Categorias");
        menuDados.add(menuCategorias);

        menuClientes.setText("Clientes");
        menuDados.add(menuClientes);

        menuEntregadores.setText("Entregadores");
        menuDados.add(menuEntregadores);

        menuTaxasEntrega.setText("Taxas de entrega");
        menuDados.add(menuTaxasEntrega);

        jMenuBar1.add(menuDados);

        menuUsuarios.setText("Usuários");

        menuUsuariosCadastro.setText("Manter usuários");
        menuUsuarios.add(menuUsuariosCadastro);

        jMenuBar1.add(menuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout areaCentralLayout = new javax.swing.GroupLayout(areaCentral);
        areaCentral.setLayout(areaCentralLayout);
        areaCentralLayout.setHorizontalGroup(
            areaCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        areaCentralLayout.setVerticalGroup(
            areaCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario)
                .addContainerGap(544, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaCentral;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JMenuItem menuBuscar;
    private javax.swing.JMenuItem menuCalcular;
    private javax.swing.JMenuItem menuCategorias;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuEntregadores;
    private javax.swing.JMenuItem menuIncluir;
    private javax.swing.JMenu menuOperacao;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuTaxasEntrega;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenuItem menuUsuariosCadastro;
    private javax.swing.JMenu menuDados;
    // End of variables declaration//GEN-END:variables
}
